title: RNDM
description: Snippets of useful things
url: "https://nsultova.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude from processing
exclude:
  - README.md
  - .git
  - .gitignore